#!/bin/bash

source $OF_SCRIPTS/bash/myRunFunctions
source config_vars

myRunApplication initializeHbPOGraph $pFlag -np $nProcs -case $eulerCaseDir
myRunApplication hbPOGraphFoam $pFlag -np $nProcs -case $eulerCaseDir
