#!/bin/bash

# Create a RBC mesh using topoSet and a RBC source mesh.

# Source run functions
source $OF_SCRIPTS/bash/myRunFunctions
source config_vars

# Copy fields to 0 directory
cd $RBCCaseDir
mkdir -p $startTime
cp 0.org/Hb.org        $startTime/Hb
cp 0.org/PO2_RBC.org   $startTime/PO2_RBC
cp 0.org/in_RBC.org    $startTime/in_RBC
cp 0.org/meshPhi.org   $startTime/meshPhi
cd ..

# Create mesh from which all RBC meshes will be generated
myRunApplication blockMesh -s $RBCSourceDir -case $RBCSourceDir

# Wipe out all cell sets
rm -f $RBCSourceDir/constant/polyMesh/sets/*
rm -f $RBCSourceDir/constant/polyMesh/cellZones*

# Create cellSet corresponding to the STL surface
myRunApplication topoSet -s $RBCSourceDir -case $RBCSourceDir

# Create cellZone
myRunApplication setsToZones -s $RBCSourceDir -case $RBCSourceDir -noFlipMap

# Use splitMeshRegions
myRunApplication splitMeshRegions -s $RBCSourceDir -case $RBCSourceDir -cellZones -overwrite

# Adjust the volume of the sample RBC mesh
myRunApplication adjustRBCMeshVolume -case $RBCSourceDir -region RBC

# Remove zones: this is essential since the zones are created by RBCMeshFactory.
# Existing zones are automatically read and cannot be deleted at run-time.
rm -rf $RBCSourceDir/constant/RBC/polyMesh/pointZones*
rm -rf $RBCSourceDir/constant/RBC/polyMesh/cellZones*
rm -rf $RBCSourceDir/constant/RBC/polyMesh/faceZones*

# clean up useless stuff
rm -rf $RBCSourceDir/$startTime/domain?
rm -rf $RBCSourceDir/constant/domain?
rm -rf $RBCSourceDir/system/domain?
rm -rf $RBCSourceDir/constant/cellToRegion*

# Decompose domain (even if empty) and fields
if [[ $isParallel == "1" ]]; then
    myRunApplication decomposePar -s $RBCCaseDir -case $RBCCaseDir
    # run again decomposePar for fields in case the method
    # writeDecomposition() crashes at the end (the division by
    # avgProcCells=0) may trigger an exception on some platforms).
    myRunApplication decomposePar -s $RBCCaseDir.fields -case $RBCCaseDir -fields
fi

touch $RBCCaseDir/$RBCCaseDir.foam
touch $RBCSourceDir/$RBCSourceDir.foam





