#!/bin/bash

source config_vars

ln -s ../../$RBCCaseDir/$startTime       $eulerCaseDir/$startTime/$RBCCaseDir
ln -s ../../$RBCCaseDir/constant         $eulerCaseDir/constant/$RBCCaseDir
ln -s ../../$RBCCaseDir/system           $eulerCaseDir/system/$RBCCaseDir

ln -s ../../$RBCSourceDir/$startTime/RBC $eulerCaseDir/$startTime/$sampleRBCDir
ln -s ../../$RBCSourceDir/constant/RBC   $eulerCaseDir/constant/$sampleRBCDir
ln -s ../../$RBCSourceDir/system         $eulerCaseDir/system/$sampleRBCDir

#- Parallel links:
if [[ $isParallel == "1" ]]; then
    echo "Making parallel links"
    cd $eulerCaseDir
    for proc in processor* ; do
        ln -s ../../../$RBCCaseDir/$proc/$startTime $proc/$startTime/$RBCCaseDir
        ln -s ../../../$RBCCaseDir/$proc/constant   $proc/constant/$RBCCaseDir
    done
    cd ..
fi
