#!/bin/bash

# Source run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions


# prepareEulerianCase.py


source config_vars
N_rbc=${#RBCDirs[@]}


./cleanCase >> log.cleanCase


./removeLinks


./prepareEulerianCase


./prepareLagrangianCases


./makeLinks


./runCase
