#!/bin/bash

source config_vars

# make a backup of the postprocessing files
if [ -d $eulerCaseDir/postProcessing ]; then
    rm -rf $eulerCaseDir/oldPostProcessing
    mv $eulerCaseDir/postProcessing $eulerCaseDir/oldPostProcessing
fi

rm -rf $eulerCaseDir/constant/tube[0-9]*
rm -rf $eulerCaseDir/constant/lumen

rm -rf $eulerCaseDir/processor*
rm -rf $RBCCaseDir/processor*

rm -rf $eulerCaseDir/[0-9][0-9]*.[0-9]*
rm -rf $eulerCaseDir/[0-9].[0-9]*
rm -rf $eulerCaseDir/[0-9][0-9]*
rm -rf $eulerCaseDir/[0-9]
rm -rf $eulerCaseDir/*e-05 $eulerCaseDir/*e-06

rm -rf $RBCCaseDir/[0-9][0-9]*.[0-9]*
rm -rf $RBCCaseDir/[0-9].[0-9]*
rm -rf $RBCCaseDir/[0-9][0-9]*
rm -rf $RBCCaseDir/[0-9]
rm -rf $RBCCaseDir/*e-05 $RBCCaseDir/*e-06

cd $eulerCaseDir/constant/polyMesh
rm -f boundary faces* owner* neighbour* points* cellZones* faceZones*
rm -f cellLevel* level0Edge* pointLevel* refinementHistory*
rm -rf sets
cd ../../..

rm -rf $sampleRBCDir/0/*

cd $sampleRBCDir/constant/polyMesh
rm -f boundary points faces owner neighbour
cd ../../..

rm -f log.*

