#!/bin/bash

source config_vars

edgeVelocityURL="https://www.zenodo.org/record/1098250/files/MVN2_edgeVelocities.gz"
RBCPathURL="https://www.zenodo.org/record/1098250/files/MVN2_RBCPaths.gz"

edgeVelocityPath="$eulerCaseDir/constant/edgeVelocities.gz"
RBCPathsPath="$eulerCaseDir/constant/RBCPaths.gz"

if [ ! -f $edgeVelocityPath ]; then
    wget $edgeVelocityURL -O $edgeVelocityPath
fi
if [ ! -f $RBCPathsPath ]; then
    wget $RBCPathURL -O $RBCPathsPath
fi
