/*---------------------------------------------------------------------------*\
  =========                 |
  \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
   \\    /   O peration     |
    \\  /    A nd           | Copyright (C) 2011-2016 OpenFOAM Foundation
     \\/     M anipulation  |
-------------------------------------------------------------------------------
License
    This file is part of OpenFOAM.

    OpenFOAM is free software: you can redistribute it and/or modify it under
    the terms of the GNU General Public License as published by the Free
    Software Foundation, either version 3 of the License, or (at your option)
    any later version.

    OpenFOAM is distributed in the hope that it will be useful, but WITHOUT ANY
    WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
    FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
    details.

    You should have received a copy of the GNU General Public License along with
    OpenFOAM.  If not, see <http://www.gnu.org/licenses/>.

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

\mainpage O2RBC, an OpenFOAM extension for oxygen transport from red blood cells

\section about About O2RBC

O2RBC is an OpenFOAM extension for the simulation of oxygen transport from
red blood cells flowing in capillaries.

\section layout O2RBC Directory Structure

Like OpenFOAM, O2RBC comprises of four main directories:
- <b>\ref srcpage "src"</b>: source code of the O2RBC libraries
- \b applications: \ref solverspage "solvers" and 
     \ref utilitiespage "utilities"
- <b> \ref tutorialspage "tutorials"</b>: test cases that illustrate the various O2RBC functionalities.
- \b doc: documentation

\section usingO2RBC Using O2RBC

- \ref installpage "Installation"
- \ref tutorialspage "Running the code"
- Postprocessing
- \ref srcpage "Source code documentation"
- \ref solverspage "Solver documentation"

\section references References

Lucker A, Weber B and Jenny P. A dynamic model of oxygen transport
from capillaries to tissue with moving red blood cells. Am J Physiol (Heart
Circ Physiol) 2014; 308(3): H206-H216

Lucker A, Secomb TW, Weber B et al. The relative influence of hematocrit
and red blood cell velocity on oxygen transport from capillaries to tissue.
Microcirculation 2017; 24: e12337. https://dx.doi.org/10.1111/micc.12337

https://www.research-collection.ethz.ch/handle/20.500.11850/181551

\*---------------------------------------------------------------------------*/

