#!/bin/bash

# Source run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions


source config_vars


./cleanCase >> log.cleanCase


./removeLinks


./prepareEulerianCase


./createRBCMesh


./makeLinks


./runCase
