#!/bin/bash

source config_vars

rm -rf $eulerCaseDir/constant/polyMesh/sets

# rm -r $eulerCaseDir/proc*
# rm -r $lagCaseDir/proc*

rm -rf $eulerCaseDir/[0-9].[0-9]*
rm -rf $eulerCaseDir/[1-9]
rm -rf $eulerCaseDir/*e-05 $eulerCaseDir/*e-06

cd $eulerCaseDir/constant/polyMesh
rm -f boundary faces owner neighbour points
cd ../../..

rm -rf $RBCCaseDir/0/*

cd $RBCSourceDir/constant/polyMesh
rm -f boundary points faces owner neighbour
cd ../../..

rm log.*

