#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

rm -rf processor*

# Get application name
application=`getApplication`

runApplication blockMesh
runApplication decomposePar
runParallel $application 2

# ----------------------------------------------------------------- end-of-file
