#!/bin/bash

# Source run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh

runApplication topoSet -dict system/topoSetDict.0
mv log.topoSet log.topoSet.0
runApplication setsToZones -noFlipMap
mv log.setsToZones log.setsToZones.0

runApplication topoSet -dict system/topoSetDict.1
mv log.topoSet log.topoSet.1
runApplication setsToZones -noFlipMap
mv log.setsToZones log.setsToZones.1

runApplication mySplitMeshRegions -cellZonesOnly -overwrite

runApplication testDisconnectedZoneMesh

