#!/bin/bash

source config_vars

cd $eulerCaseDir

rm -rf $startTime/$RBCCaseDir
rm -rf constant/$RBCCaseDir
rm -rf system/$RBCCaseDir

rm -rf constant/$sampleRBCDir
rm -rf system/$sampleRBCDir

rm -rf constant/RBCBaseGeometricState

#- Parallel links:
echo "Removing parallel links"
for proc in processor* ; do
    rm -rf $proc/$startTime/$RBCCaseDir
    rm -rf $proc/constant/$RBCCaseDir

    rm -rf $proc/$startTime/$sampleRBCDir
    rm -rf $proc/constant/$sampleRBCDir
done

cd ..

