#!/bin/bash

source config_vars

cd $eulerCaseDir

rm -r $startTime/$RBCCaseDir
rm -r constant/$RBCCaseDir
rm -r system/$RBCCaseDir

rm -r constant/$sampleRBCDir
rm -r system/$sampleRBCDir

rm -r constant/RBCBaseGeometricState

#- Parallel links:
echo "Removing parallel links"
for proc in processor* ; do
    rm -rf $proc/$startTime/$RBCCaseDir
    rm -rf $proc/constant/$RBCCaseDir

    rm -rf $proc/$startTime/$sampleRBCDir
    rm -rf $proc/constant/$sampleRBCDir
done

cd ..

